// Catalogue statique : aéroports et compagnies utilisés pour simuler des vols.

export const AIRPORTS = [
  { iata: "CDG", city: "Paris", name: "Charles de Gaulle", country: "France", lat: 49.0097, lon: 2.5479 },
  { iata: "ORY", city: "Paris", name: "Orly", country: "France", lat: 48.7262, lon: 2.3652 },
  { iata: "NCE", city: "Nice", name: "Côte d'Azur", country: "France", lat: 43.6584, lon: 7.2159 },
  { iata: "LYS", city: "Lyon", name: "Saint-Exupéry", country: "France", lat: 45.7256, lon: 5.0811 },
  { iata: "MRS", city: "Marseille", name: "Provence", country: "France", lat: 43.4393, lon: 5.2214 },
  { iata: "TLS", city: "Toulouse", name: "Blagnac", country: "France", lat: 43.6293, lon: 1.3638 },
  { iata: "BOD", city: "Bordeaux", name: "Mérignac", country: "France", lat: 44.8283, lon: -0.7156 },
  { iata: "LHR", city: "Londres", name: "Heathrow", country: "Royaume-Uni", lat: 51.47, lon: -0.4543 },
  { iata: "AMS", city: "Amsterdam", name: "Schiphol", country: "Pays-Bas", lat: 52.3105, lon: 4.7683 },
  { iata: "FRA", city: "Francfort", name: "Francfort-sur-le-Main", country: "Allemagne", lat: 50.0379, lon: 8.5622 },
  { iata: "MAD", city: "Madrid", name: "Barajas", country: "Espagne", lat: 40.4983, lon: -3.5676 },
  { iata: "BCN", city: "Barcelone", name: "El Prat", country: "Espagne", lat: 41.2974, lon: 2.0833 },
  { iata: "LIS", city: "Lisbonne", name: "Humberto Delgado", country: "Portugal", lat: 38.7742, lon: -9.1342 },
  { iata: "FCO", city: "Rome", name: "Fiumicino", country: "Italie", lat: 41.8003, lon: 12.2389 },
  { iata: "MXP", city: "Milan", name: "Malpensa", country: "Italie", lat: 45.63, lon: 8.7231 },
  { iata: "ZRH", city: "Zurich", name: "Zurich", country: "Suisse", lat: 47.4647, lon: 8.5492 },
  { iata: "BRU", city: "Bruxelles", name: "Bruxelles-National", country: "Belgique", lat: 50.9014, lon: 4.4844 },
  { iata: "ATH", city: "Athènes", name: "Elefthérios-Venizélos", country: "Grèce", lat: 37.9364, lon: 23.9445 },
  { iata: "IST", city: "Istanbul", name: "Istanbul", country: "Turquie", lat: 41.2753, lon: 28.7519 },
  { iata: "CMN", city: "Casablanca", name: "Mohammed V", country: "Maroc", lat: 33.3675, lon: -7.5898 },
  { iata: "RAK", city: "Marrakech", name: "Ménara", country: "Maroc", lat: 31.6069, lon: -8.0363 },
  { iata: "TUN", city: "Tunis", name: "Tunis-Carthage", country: "Tunisie", lat: 36.851, lon: 10.2272 },
  { iata: "ALG", city: "Alger", name: "Houari Boumediene", country: "Algérie", lat: 36.691, lon: 3.2154 },
  { iata: "DKR", city: "Dakar", name: "Blaise Diagne", country: "Sénégal", lat: 14.67, lon: -17.0733 },
  { iata: "DXB", city: "Dubaï", name: "Dubai International", country: "Émirats arabes unis", lat: 25.2532, lon: 55.3657 },
  { iata: "DOH", city: "Doha", name: "Hamad", country: "Qatar", lat: 25.2731, lon: 51.6081 },
  { iata: "JFK", city: "New York", name: "John F. Kennedy", country: "États-Unis", lat: 40.6413, lon: -73.7781 },
  { iata: "LAX", city: "Los Angeles", name: "Los Angeles International", country: "États-Unis", lat: 33.9416, lon: -118.4085 },
  { iata: "MIA", city: "Miami", name: "Miami International", country: "États-Unis", lat: 25.7959, lon: -80.287 },
  { iata: "YUL", city: "Montréal", name: "Pierre-Elliott-Trudeau", country: "Canada", lat: 45.4706, lon: -73.7408 },
  { iata: "GRU", city: "São Paulo", name: "Guarulhos", country: "Brésil", lat: -23.4356, lon: -46.4731 },
  { iata: "NRT", city: "Tokyo", name: "Narita", country: "Japon", lat: 35.772, lon: 140.3929 },
  { iata: "BKK", city: "Bangkok", name: "Suvarnabhumi", country: "Thaïlande", lat: 13.69, lon: 100.7501 },
  { iata: "SIN", city: "Singapour", name: "Changi", country: "Singapour", lat: 1.3644, lon: 103.9915 },
  { iata: "RUN", city: "La Réunion", name: "Roland-Garros", country: "France", lat: -20.8871, lon: 55.5103 },
  { iata: "PTP", city: "Pointe-à-Pitre", name: "Pôle Caraïbes", country: "France", lat: 16.2653, lon: -61.5318 },
];

// type: "full" = compagnie classique, "low" = low-cost (court/moyen-courrier uniquement)
// factor : multiplicateur de prix autour de la base
export const AIRLINES = [
  { code: "AF", name: "Air France", type: "full", factor: 1.1 },
  { code: "KL", name: "KLM", type: "full", factor: 1.05 },
  { code: "LH", name: "Lufthansa", type: "full", factor: 1.12 },
  { code: "BA", name: "British Airways", type: "full", factor: 1.1 },
  { code: "IB", name: "Iberia", type: "full", factor: 0.98 },
  { code: "TP", name: "TAP Air Portugal", type: "full", factor: 0.95 },
  { code: "LX", name: "Swiss", type: "full", factor: 1.18 },
  { code: "TK", name: "Turkish Airlines", type: "full", factor: 0.9 },
  { code: "EK", name: "Emirates", type: "full", factor: 1.15, minKm: 2500 },
  { code: "QR", name: "Qatar Airways", type: "full", factor: 1.08, minKm: 2500 },
  { code: "DL", name: "Delta", type: "full", factor: 1.0, minKm: 4000 },
  { code: "AC", name: "Air Canada", type: "full", factor: 0.97, minKm: 4000 },
  { code: "U2", name: "easyJet", type: "low", factor: 0.62 },
  { code: "FR", name: "Ryanair", type: "low", factor: 0.5 },
  { code: "TO", name: "Transavia", type: "low", factor: 0.58 },
  { code: "VY", name: "Vueling", type: "low", factor: 0.6 },
];
